POST http://localhost:3000/api/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMGVhNmMwOTgyZGVlMmEwNDQ1NTZkOCIsInVzZXJuYW1lIjoianVsZW5iZXJvIiwiaWF0IjoxNjI4MzYwNjM4LCJleHAiOjE2Mjg5NjU0Mzh9.ZQ-ufq-_IMcGkR_sl0gWslfXlwizCRlOT_vL_jfGcaI

{
    "eventName" : "Evento Prueba 2",
	"location"  : "Bogota",
	"datesEvent" : [{"date" : "2021-08-10T14:00:00", "price" : 50},{"date" : "2021-08-12T20:30:00", "price" : 60.75}],
    "resume": "Evento Programado por Cadena Radial Pepito",
	"image" : "http://lorempixel.com/640/480/fashion/",
	"outstanding" : true
}

###
POST http://localhost:3000/api/events
Content-Type: application/json

{
    "eventName" : "Evento Prueba 2",
	"location"  : "Bogota",
	 "datesEvent" : [{"date" : "2021-08-10T14:00:00", "price" : 50},{"date" : "2021-08-12T20:30:00", "price" : 60.75}],
    "resume": "Evento Programado por Cadena Radial Pepito",
	"image" : "http://lorempixel.com/640/480/fashion/",
	"outstanding" : true
}

###
GET http://localhost:3000/api/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMTBhMGNkMjM4NjIzNjYwNDQyODA3MiIsInVzZXJuYW1lIjoiYmF0bWFuIiwiaWF0IjoxNjI4NDc5NzIxLCJleHAiOjE2MjkwODQ1MjF9.vj6pruvZFBzv7j-OYIMUU8HlE12JQljWW3SlWLK2l2g

###
GET http://localhost:3000/api/events?pag=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMTBhMGNkMjM4NjIzNjYwNDQyODA3MiIsInVzZXJuYW1lIjoiYmF0bWFuIiwiaWF0IjoxNjI4NDc5NzIxLCJleHAiOjE2MjkwODQ1MjF9.vj6pruvZFBzv7j-OYIMUU8HlE12JQljWW3SlWLK2l2g

###
GET http://localhost:3000/api/events

###
GET http://localhost:3000/api/events/610cb8713463e63c7826d64c


###
GET http://localhost:3000/api/events/twitter/610cb54165d19e2e60f40520

